CREATE TABLE properties(
property_id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
type TEXT NOT NULL,
price REAL NOT NULL,
location TEXT NOT NULL,
bedroom INTEGER NOT NULL,
bathrooms INTEGER NOT NULL,
area INTEGER NOT NULL,
descriotion TEXT NOT NULL,
created_at TEXT DEFAULT CURRENT_TIMESTAMP,
updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
is_available INTEGER DEFAULT 1
);