# Generated by Django 5.2.8 on 2025-12-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='photo',
            new_name='photos',
        ),
    ]
