# Generated by Django 5.2.8 on 2025-12-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_photo_employee_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('contact', models.IntegerField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
